<h2>Ajoutez un nouveau produit</h2>

<form method="post">
    <div class="form-group">
        <label for="exampleInputEmail1">Nom</label>
        <input type="text" name="nom" required class="form-control" value="<?=$product->getNom()?>" />
    </div>

            
    <div class="form-group">
        <label for="exampleInputEmail1">Description</label>
        <input type="text" name="description" required class="form-control" value="<?=$product->getDescription() ?>" />
    </div>

            
    <div class="form-group">
        <label for="exampleInputEmail1">Prix</label>
        <input type="text" name="prix" class="form-control" value="<?=$product->getPrix() ?>" >
    </div>

            
    <div class="form-group">
        <label for="exampleInputEmail1">Stock</label>
        <input type="text" name="stock" class="form-control" value="<?=$product->getStock() ?>"/>
    </div>

            
    <!--<div class="form-group">
        <label for="exampleInputEmail1">Categorie</label>
        <input type="text" name="categorie" class="form-control" value="<?=$product->getCategorie() ?>" >
    </div> -->
     <div class="form-group">
        <label for="exampleInputEmail1">Categorie</label>
        <select name="categorie" id="" class="form-select">
            <?php foreach($categories as $categorie): ?>
                <option value="<?= $categorie->getId() ?>" <?= ($categorie->getId() == $product->getCategorie()) ? 'selected' : '' ?> ><?= $categorie->getNom() ?></option>
            <?php endforeach; ?>
        </select>
    </div>
            
            
    <div class="form-group">
        <label for="exampleInputEmail1">Image</label>
        <input type="file" name="image" class="form-control" value="<?=$product->getImage() ?>">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>