
<h2 class="text-center">Connectez-vous</h2>

<form method="post">
        
    <div class="form-group">
        <label for="exampleInputEmail1">Email</label>
        <input type="text" name="email" value="samassa@gmail.com" class="form-control">
    </div>

        
    <div class="form-group">
        <label for="exampleInputEmail1">Password</label>
        <input type="password" name="password" value="1234" class="form-control">
    </div>

    <button type="submit" class="btn btn-primary mt-2">Submit</button>
</form>