<h2 class="text-center">Liste des clients</h2>

<a href="?actionUser=new" class="btn btn-primary my-2">Ajouter</a>

<table class="table table-striped">
        <tr class="table-primary">
            <th>Nom</th>
            <th>Prénom</th>
            <th>Email</th>
            <th>Mot de passe</th>
            <th>Adresse</th>
            <th>Télephone</th>
            <th>Date</th>
            <th>Action</th>
        </tr>

        <?php foreach ($users as $user): ?>
            <tr>
                <td><?=$user->getNom() ?></td>
                <td><?=$user->getPrenom() ?></td>
                <td><?=$user->getEmail() ?></td>
                <td><?=$user->getPassword() ?></td>
                <td><?=$user->getAdresse() ?></td>
                <td><?=$user->getTelephone() ?></td>
                <td><?=$user->getDateInscription() ?></td>
                <td>
                    <a href="?actionUser=update&id=<?=$user->getId() ?>"><i class="fa-solid fa-pen"></i></a> |
                    <a href="?actionUser=delete&id=<?=$user->getId() ?>"><i class="fa-solid fa-trash"></i></a> |
                    <a href="?actionUser=show&id=<?=$user->getId() ?>"><i class="fa-solid fa-eye"></i></a>
                </td>

            </tr>
        <?php endforeach; ?>

</table>