<h2 class="text-center">Inscrivez-vous</h2>

<form method="post">
    <div class="form-group">
        <label for="exampleInputEmail1">Nom</label>
        <input type="text"  name="nom" class="form-control" value="<?= $user->getNom() ?>">
    </div>

    <div class="form-group">
        <label for="exampleInputEmail1">Prénom</label>
        <input type="text"  name="prenom" class="form-control" value="<?= $user->getPrenom() ?>">
    </div>

    <div class="form-group">
        <label for="exampleInputEmail1">Email</label>
        <input type="text" name="email" required class="form-control" value="<?= $user->getEmail() ?>">
    </div>
                
                
    <div class="form-group">
        <label for="exampleInputEmail1">Password</label>
        <input type="password" name="password" required class="form-control">
    </div>

    <div class="form-group">
        <label for="exampleInputEmail1">Adresse</label>
        <input type="text" name="adresse" class="form-control" value="<?= $user->getAdresse() ?>">
    </div>
                
    <div class="form-group">
        <label for="exampleInputEmail1">Télephone</label>
        <input type="number" name="telephone" class="form-control" value="<?= $user->getTelephone() ?>">
    </div>
                

    <button type="submit" class="btn btn-primary mt-2">Submit</button>
</form>

