<h2 class="text-center">Ajouter un nouveau client</h2>

    <form method="post">
        <div class="form-group">
            <label for="exampleInputEmail1">Nom</label>
            <input type="text" name="nom" required class="form-control" value="<?=$user->getNom()?>" />
        </div>

        
        <div class="form-group">
            <label for="exampleInputEmail1">Prénom</label>
            <input type="text" name="prenom" required class="form-control" value="<?=$user->getPrenom() ?>" />
        </div>

        
        <div class="form-group">
            <label for="exampleInputEmail1">Email</label>
            <input type="text" name="email" class="form-control" value="<?=$user->getEmail() ?>" >
        </div>

        
        <div class="form-group">
            <label for="exampleInputEmail1">Password</label>
            <input type="password" name="password" class="form-control" required />
        </div>

        
        <div class="form-group">
            <label for="exampleInputEmail1">Adresse</label>
            <input type="text" name="adresse" class="form-control" value="<?=$user->getAdresse() ?>" >
        </div>
        
        
        <div class="form-group">
            <label for="exampleInputEmail1">Télephone</label>
            <input type="tel" name="telephone" class="form-control" value="<?=$user->getTelephone() ?>">
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>