<h2>Ajoutez une nouvelle comande</h2>

<form method="post">        
    <div class="form-group">
        <label for="exampleInputEmail1">Statut</label>
        <input type="text" name="statut" class="form-control" value="<?=$order->getStatut() ?>" />
    </div>
            
    <div class="form-group">
        <label for="exampleInputEmail1">Montant total</label>
        <input type="text" name="total_montant" class="form-control" value="<?=$order->getTotalMontant() ?>" >
    </div>

    <div class="form-group">
        <label for="exampleInputEmail1">User</label>
        <select name="user" id="" class="form-select">
            <?php foreach($users as $user): ?>
                <option value="<?= $user->getId() ?>" <?= ($user->getId() == $order->getUser()) ? 'selected' : '' ?> ><?= $user->getPrenom() ?></option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="form-group">
        <label for="exampleInputEmail1">Date de commande</label>
        <input type="date" name="date_commande" required class="form-control" value="<?=$order->getDateCommande()?>" />
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>