<h2 class="text-center">Liste des catégories</h2>

<a href="?actionCat=new" class="btn btn-primary my-2">Ajouter</a>

<table class="table table-striped">
        <tr class="table-primary">
            <th>Nom</th>
            <th>Description</th>
            <th>Action</th>
        </tr>

        <?php foreach ($categories as $categorie): ?>
            <tr>
                <td><?=$categorie->getNom() ?></td>
                <td><?=$categorie->getDescription() ?></td>
                <td>
                    <a href="?actionCat=update&id=<?=$categorie->getId() ?>"><i class="fa-solid fa-pen"></i></a> |
                    <a href="?actionCat=delete&id=<?=$categorie->getId() ?>"><i class="fa-solid fa-trash"></i></a> |
                    <a href="?actionCat=show&id=<?=$categorie->getId() ?>"><i class="fa-solid fa-eye"></i></a>
                </td>

            </tr>
        <?php endforeach; ?>

</table>