<h2 class="text-center">Ajouter un nouveau client</h2>

    <form method="post">
        <div class="form-group">
            <label for="exampleInputEmail1">Nom</label>
            <input type="text" name="nom" required class="form-control" value="<?=$categorie->getNom()?>" />
        </div>

        
        <div class="form-group">
            <label for="exampleInputEmail1">Description</label>
            <input type="text" name="description" required class="form-control" value="<?=$categorie->getDescription() ?>" />
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>