<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">
    <title>Projet fin d'année</title>
</head>
<body>

<header class="bg-light">

    <nav class="navbar navbar-expand-lg bg-light">
        <a href="." class="btn btn-outline-primary">Accueil</a>
        <a href="?actionUser=user" class="btn btn-outline-primary">User</a>
        <a href="?actionProd=product" class="btn btn-outline-primary">Product</a>
        <a href="?actionCat=categorie" class="btn btn-outline-primary">Categorie</a>
        <a href="?actionOrd=order" class="btn btn-outline-primary">Commande</a>
        <a href="?actionPan=panier" class="btn btn-outline-primary">Panier</a>
        <a href="?actionUser=inscription" class="btn btn-outline-primary">Inscription</a>
        <a href="?actionUser=connexion" class="btn btn-outline-primary">Connexion</a>
        <a href="?actionUser=deconnexion" class="btn btn-outline-danger">déconnexion</a>
    </nav>

</header>
<main>

