<h2>Ajoutez un nouveau panier</h2>

<form method="post">        
    <div class="form-group">
        <label for="exampleInputEmail1">Quantite</label>
        <input type="text" name="quantite" class="form-control" value="<?=$panier->getQuantite() ?>" />
    </div> 


            
    <div class="form-group">
        <label for="exampleInputEmail1">User</label>
        <select name="user" id="" class="form-select">
            <?php foreach($users as $user): ?>
                <option value="<?= $user->getId() ?>" <?= ($user->getId() == $panier->getUser()) ? 'selected' : '' ?> ><?= $user->getPrenom() ?></option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="form-group">
        <label for="exampleInputEmail1">Produit</label>
        <select name="product" id="" class="form-select">
            <?php foreach($products as $product): ?>
                <option value="<?= $product->getId() ?>" <?= ($product->getId() == $panier->getProduct()) ? 'selected' : '' ?> ><?= $product->getNom() ?></option>
            <?php endforeach; ?>
        </select>
    </div>

    <!--<div class="form-group">
        <label for="exampleInputEmail1">Date</label>
        <input type="date" name="date_ajout" required class="form-control" value="<?=$panier->getDateAjout()?>" />
    </div>-->

    <button type="submit" class="btn btn-primary">Submit</button>
</form>